version: '3.3'
services:
  orders:
    container_name: orders-container
    image: orders-container
    build: orders/
    ports:
      - "9090:9090"
    depends_on:
      - stock
  stock:
    container_name: stock-container
    image: stock
    build: gestionProduct/
    ports:
      - "9091:9091"
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=orders_db

networks:
  default:
    name: app-cloud-feign-net

